### ISSUE TITLE
Cannot create Docs.json

### ISSUE THREAD

**Issue by Maxmyd** [adepierre/ficsit-companion#1]
Hello,
I understand this issue is not much related to this exact application but I cannot locate Docs.json file. I installed FModel and could open and browse game files. But when it comes to search for that file, I cannot. Can you please provide **a bit** more information on this?
Thank you so much for this tool! Wish you have enough time to develop it.

**Comment by adepierre** [comment]
Hello, you'll find informations about this file (and all the other ones provided by the developers of the game) in this [wiki page](https://satisfactory.wiki.gg/wiki/Community_resources)

**Comment by Maxmyd** [comment]
Thank you for the link! Can I suggest you to add this link to "Updated" paragraph, somewhere after the link to ficsit.app? So not so smart persons like me would have not asked the questions like this :)
