### ISSUE TITLE
100% CPU usage when GPU acceleration is disabled in the browser

### ISSUE THREAD

**Issue by gitishi** [adepierre/ficsit-companion#14]
I get 100% CPU usage when the GPU acceleration setting is disabled in chrome.
I was wondering why sometimes my PCs fans started going crazy until I noticed it was this app in my browser.

Maybe you can detect this browser setting and give out an error or limit the fps, or add something to the README, in case you can't change it.

**Comment by adepierre** [comment]
Oh indeed it relies on vsync to limit the FPS so if GPU is disabled there is no limit anymore. Thanks for the report!
