### ISSUE TITLE
Nitro Rocket fuel is incorrect

### ISSUE THREAD

**Issue by MaddJhin** [adepierre/ficsit-companion#15]
The ratios for nitro rocket fuel are all wrong. 

It should be (in the game)

100 m³/min of Fuel
100 units/min of Sulfur
75 m³/min of Nitrogen Gas
50 units/min coal

It currently is (in ficsit companion)

120 m³/min of Fuel
120 units/min of Sulfur
90 m³/min of Nitrogen Gas
60 units/min coal

**Comment by adepierre** [comment]
Oh thanks for the report. That's weird cause it's taken directly from the game files. Maybe they changed the value since the release of 1.0 or the file was not up to date with the in-game values 🤔
